Auto-collapse sub-lists on initial list expansion
parameter1/company-update pull request #16
Opened 2022-11-02 15:25 UTC by Shinsina

2022-11-14 20:10 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Collapse Directory Category subcategories if they have additional subcategories by default](https://trello.com/c/tLf7CACR/339-collapse-directory-category-subcategories-if-they-have-additional-subcategories-by-default)

2022-11-15 18:23 UTC, solocommand requested changes

2022-11-15 18:23 UTC, solocommand commented on services/app/app/templates/components/directory/category-tree.hbs
> +    {{#if noChildren}}
You don't need to create a computed property for this, just use the `unless` control structure to negate an if -- `#unless node.children.length`.

2022-11-15 18:23 UTC, solocommand commented on services/app/app/templates/components/directory/category-tree.hbs
> +      {{entypo-icon "chevron-right" class="mr-2"}}
No need for computed properties for this, just use an inline ternary -- 
```
{{ entypo collapsed ? "chevron-right" : "chevron-down" ... }}
```

2022-11-15 18:23 UTC, solocommand commented on services/app/app/templates/components/directory/category-tree.hbs
> +  {{#if expandedState }}
Remove extra prop

2022-11-15 18:23 UTC, solocommand commented on services/app/app/components/directory/category-tree.js
> +export default Component.extend(ActionMixin, {
This component doesn't do any loading state manipulation -- why is this mixin being included?

2022-11-15 18:23 UTC, solocommand commented on services/app/app/components/directory/category-tree.js
> +    return false
Don't use (and overwrite) a computed property for this purpose. Instead, set the value for `collapsed` on init to a boolean based on `node.children.length`. Something like this:
```js
collapsed: true,
// ...
init() {
  this.collapsed = Boolean(getAsArray(node, 'children').length)
},
```

2022-11-15 20:27 UTC, merged