Only display Leadership pages/options if a company is marked as a Leader
parameter1/company-update pull request #17
Opened 2022-11-17 18:34 UTC by Shinsina

WARNING: This is a workflow change that impacts ALL TENANTS requiring that if a company should be able to update their leadership information they must at least be scheduled to the root leaders alias for the respective publication prior to their company update link being sent out (something to that effect), I believe this should **not** be configurable as it would be adding yet another configuration option to an already bloated list of configuration options (most of which are already for Leaders to begin with, see https://github.com/parameter1/company-update/blob/master/services/graphql/src/env.js) and I believe is in line with the expectations potentially outlined in more cases than not as to how this form works on the whole. 

Feedback I'm looking for is if somehow a user (of any kind from anywhere) lands on `port/COMPANY_HASH/leadership` should anything more than a blank page be displayed? There would no longer be a way to navigate to this page unless someone got lucky by figuring out the pathing or has it cached in their browser and is no longer a leader etc. etc.

Portal Homepage NOT LEADER:
![Screenshot from 2022-11-17 12-06-29](https://user-images.githubusercontent.com/46794001/202529250-4af4c938-3a69-4472-b7e1-19de72b028e3.png)

Portal Homepage LEADER:
![Screenshot from 2022-11-17 12-06-41](https://user-images.githubusercontent.com/46794001/202529253-1014f4cc-42bb-48eb-a126-3156805b715c.png)

Leadership Page NOT LEADER:
![Screenshot from 2022-11-17 12-19-42](https://user-images.githubusercontent.com/46794001/202529399-068426e6-475d-4671-a439-88c3627893e1.png)

Leadership Page LEADER:
![Screenshot from 2022-11-17 12-19-32](https://user-images.githubusercontent.com/46794001/202529507-ae61715d-a65d-4bb0-a2a4-9f226ae7a9f3.png)

2022-11-17 18:35 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow configuration of display of Leaders on Company Update form only if the Company "is a leader"](https://trello.com/c/w0Q63uc9/152-allow-configuration-of-display-of-leaders-on-company-update-form-only-if-the-company-is-a-leader)

2022-11-17 20:01 UTC, solocommand requested changes
@Shinsina There are a couple of structural issues to address, but this _must_ be an opt-in configurable option, not a change made across the board. Existing customers have this already deployed with expected functionality, and at least one (AB Media) uses it to add companies to the leaders program, not just update the selections.

The out-of-the-box solution that is _supposed_ to be used for selecting which companies are allowed to see the leadership submission segment is the `leadershipCompanyLabel` config.

2022-11-17 20:01 UTC, solocommand commented on services/app/app/controllers/portal/index.js
> +    }
I don't know why this was implemented this way, but the logic should be:
- if not enabled, return false
- if <new leaders-only config> check if the model is scheduled to the appropriate section
- if leadership company label is present, check if the model has the label
- return true

2022-11-17 20:01 UTC, solocommand commented on services/app/app/gql/queries/portal.graphql
> -# import CompanyListFragment from "../fragments/company/list"
The fragment should not be removed, just add your new field after it is spread.

2022-11-17 20:01 UTC, solocommand commented on services/app/app/templates/portal/leadership.hbs
> -<div class="card mb-4">
This should not be wrapped in an `if` tag, now the page just looks broken.

If the user is not allowed to submit leadership selections (due to the `leadershipEnabled` controller prop being false above), they should receive a popup notification (the thing that happens on save but as an error instead of success message), the transition should be aborted, and they should be redirected to the company portal page.

2022-11-17 20:55 UTC, Shinsina commented
> @Shinsina There are a couple of structural issues to address, but this _must_ be an opt-in configurable option, not a change made across the board. Existing customers have this already deployed with expected functionality, and at least one (AB Media) uses it to add companies to the leaders program, not just update the selections.
> 
> The out-of-the-box solution that is _supposed_ to be used for selecting which companies are allowed to see the leadership submission segment is the `leadershipCompanyLabel` config.

@solocommand Want to start out in saying I ultimately don't care how we handle this but I want the reasoning/rationale and most importantly the expected behavior provided a specific company criteria to be consistent, my understanding via previous discussions was to "make the form logic and the site logic the same for determining who is or is not a leader" and this would be doing that. 

The `leaderCompanyLabel` concept is only found within this form and doesn't provide any sort of qualifications elsewhere as to "who is or is not a leader" which adds potential points of confusion as to "who is what and how". If ultimately we would rather use labels for determining that logic, my personal opinion would be to do that everywhere but as it stands currently that isn't how it works and I understand there is more to it than just flipping logic one way or the other.

Additionally, I wasn't able to find anyone using `leadershipCompanyLabel`, it's possible I missed it in glancing over the Rancher configurations for this, if you could let me know by whatever means as to who is currently using the form in that fashion, would be much appreciated. 

Ultimately another additional configuration option to opt into this behavior (showing leaders only to companies that meet `isLeaders` criteria) is fine but I would rather we use existing behavior (such as the labels) than creating new behavior (which is what this is currently doing at least from the form side).

2022-11-17 20:57 UTC, Shinsina commented on services/app/app/templates/portal/leadership.hbs
> -<div class="card mb-4">
Appreciate the direction on this, I just knew I needed to do something to "stop" but I wasn't sure what the expectation would/should be in terms of what was supposed to happen. I did note this in my initial PR comment as something I was looking for feedback on and will work on correcting it accordingly

2022-11-17 21:07 UTC, Shinsina commented on services/app/app/gql/queries/portal.graphql
> -# import CompanyListFragment from "../fragments/company/list"
Oversight on my part trying to sort out how to handle the input, resolved.

2022-11-17 21:11 UTC, Shinsina commented on services/app/app/controllers/portal/index.js
> +    }
I think I sorted this out but it's possible I misread/misunderstood the order of operations on this, lemme know!

2022-11-18 17:36 UTC, Shinsina commented on services/app/app/templates/portal/leadership.hbs
> -<div class="card mb-4">
Corrected, here is what the verbiage for that "error" message looks like currently, not entirely sure what we want to put here but better than nothing.

![Screenshot from 2022-11-18 11-35-42](https://user-images.githubusercontent.com/46794001/202767142-fcefc73c-d897-4867-9513-733dccd299a7.png)

2022-11-18 18:21 UTC, solocommand commented on services/app/app/templates/portal/leadership.hbs
> -<div class="card mb-4">
I would go keep it short and go with
> Sorry, leadership updates are unavailable for this company.

If they have a contact link defined, add 
> [Click here]() to contact us if you need help!

2022-11-18 20:54 UTC, Shinsina commented on services/app/app/templates/portal/leadership.hbs
> -<div class="card mb-4">
![Screenshot from 2022-11-18 14-51-41](https://user-images.githubusercontent.com/46794001/202800279-2ff6edd8-bcde-4f55-83c7-e54e68de0ccb.png)
![Screenshot from 2022-11-18 14-54-17](https://user-images.githubusercontent.com/46794001/202800619-8f7b1153-94c9-41d3-9e27-607c9bca8cc6.png)

2022-11-28 14:54 UTC, Shinsina commented
@solocommand In the current state I've opted to just use the existing label configuration option, this separates the logic of "Leaders Eligible" from "Is a Leader" entirely so as not to cause potential points of conflict or confusion as to who gets what and how between this and the site.

2025-06-03 15:15 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Enable site-limited Leaders selection within the Company Update Form](https://trello.com/c/zMglUM3B/474-enable-site-limited-leaders-selection-within-the-company-update-form)

2025-06-03 15:16 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Hide "Modify Product Promotions" and "Modify Leadership Categories" if company isn't Leaders-enabled](https://trello.com/c/CNImB4uR/475-hide-modify-product-promotions-and-modify-leadership-categories-if-company-isnt-leaders-enabled)

2025-06-05 12:40 UTC, merged