Addition of form portion to allow updates to online directory sections when configured
parameter1/company-update pull request #24
Opened 2023-04-24 16:51 UTC by Shinsina

Mostly copy and paste from the existing logic pertaining to Leaders albeit with a separate config options, route, etc.

![Screenshot from 2023-04-24 11-47-21](https://user-images.githubusercontent.com/46794001/234063481-a3d1a600-d956-4904-9109-7a6c321830a3.png)

2023-04-24 16:51 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Enable Directory and Leaders portion of Company Update Form](https://trello.com/c/QVgJzr1j/145-enable-directory-and-leaders-portion-of-company-update-form)

2023-05-09 15:23 UTC, B77Mills approved these changes
@solocommand I did spin this and test it, but am lookin for a second set of eyes on this.  Could you give it a quick look please

2023-05-09 15:23 UTC, B77Mills approved these changes
@solocommand I did spin this and test it, but am lookin for a second set of eyes on this.  Could you give it a quick look please

2023-05-09 15:26 UTC, B77Mills commented on services/graphql/src/env.js
> +  ONLINE_DIRECTORY_SCHEDULED_SITE_ONLY: bool({ desc: 'If leadership sections should be limited sites that have schedules.', default: false }),
@Shinsina Can you update the description here

2023-05-09 21:18 UTC, solocommand requested changes
Several changes here -- primarily using the terminology of `directorySections` instead of `onlineDirectory` and fixing how the data is submitted/reviewed.

`directory` should have been implemented as `directoryCategories`, but we didn't have a non-taxonomy version of the directory at that time...just leave that alone for now, but follow the new naming structure.

You're going to need to create a new type of submission -- do not re-use the leadership or directory category types. You can reuse the icon but pretty much everything else should be re-created.

You're also going to need to create new portal components to display the sections due to differing requirements for the directory vs leaders. You can start by copying the leadership components and removing the max.

You'll have to create new review-mode templates/controllers for directory sections, and you're also going to have to add it to the GraphQL enum and mutations.

For a general outline of everything that needs to be modified on the back-end to support a new submission type, review #15.

2023-05-09 21:18 UTC, solocommand commented on services/app/app/routes/portal/directory-sections.js
> +    this.controllerFor('portal.directory-sections').set('categories', ids);
This should be sections, not categories.

2023-05-09 21:18 UTC, solocommand commented on services/app/app/templates/portal/directory-sections.hbs
> +      {{leadership/site site=site selectedIds=categories onUpdate=(action "update")}}
Create new components for directory sections, don't re-use the leadership components. These can have independent rules -- for example the leadershipSectionMax is a limitation of the leaders program, and shouldn't be used with directory scheduling.

2023-05-09 21:18 UTC, solocommand commented on services/app/app/templates/portal/directory-sections.hbs
> +}}
This needs to be created for directory sections, not reusing categories or leadership modals.

2023-05-09 21:18 UTC, solocommand commented on services/app/app/templates/portal/index.hbs
> +    {{#if onlineDirectoryEnabled}}
I'd prefer if we used `directorySections` as the prefix for everything instead of `onlineDirectory`.

2023-05-09 21:18 UTC, solocommand commented on services/app/app/controllers/portal/directory-sections.js
> +    this.set('categories', []);
This should be `sections` in this context.

2023-05-10 20:04 UTC, solocommand requested changes
A few final changes, overall looking in good shape.

2023-05-10 20:04 UTC, solocommand commented on services/graphql/src/env.js
> +  DIRECTORY_SECTIONS_MAX: num({ desc: 'The maximum number of online directory sections that can be selected per site.', default: 3 }),
This env can be removed, no longer used elsewhere

2023-05-10 20:04 UTC, solocommand commented on services/app/app/routes/list.js
> +    return model.map((item) => {
Performing modifications to the Ember model can sometimes mess up event subscriptions, so it's generally frowned upon. If I'm reading this correctly, you're doing this map to clean up the presentation of the submission type?

If that's the case, do this in the template/presentation layer. You can use a HTMLBars template helper when printing text by using `|` -- such as `{{ submission.label | myHelperName }}`. Helpers are loaded automatically from the `./helpers` folder.

You can also use the [titleize](https://github.com/romulomachado/ember-cli-string-helpers#titleize) helper from the `ember-cli-string-helpers` package, although I'm not sure if it's been added to this project yet or not.

2023-05-10 20:04 UTC, solocommand commented on services/app/app/components/directory-sections-review/section.js
> +  }),
Review everywhere `canSelect` is used -- in the original components this was based off of the current/max number selected. In fact, I'm pretty sure you can remove this everywhere on the new components -- and any properties that depend on it like this one. In this case, if `canSelect` is not passed through (likely from the controller), the control should behave as if it is disabled.

2023-05-10 20:04 UTC, solocommand commented on services/app/app/templates/review/directory-sections.hbs
> +    <p>For each section, review the selected sections. Each section and will have a toggle icon ({{entypo-icon "check" class="border m-1 p-1 text-success"}} / {{entypo-icon "cross" class="border m-1
```suggestion
    <p>For each section, review the selected directory sections. Each section will have a toggle icon ({{entypo-icon "check" class="border m-1 p-1 text-success"}} / {{entypo-icon "cross" class="border m-1 p-1 text-danger"}}) next to the field. For each field, verify that the submitted value is acceptable, or use the toggle to ignore the field.</p>
```

2023-05-11 14:46 UTC, solocommand approved these changes

2023-05-11 14:47 UTC, merged