Allow configuration of required fields for company details form, add `publicEmail`
parameter1/company-update pull request #28
Opened 2023-08-14 20:15 UTC by Shinsina

**REQUIRES: https://github.com/parameter1/base-cms/pull/767 to be deployed to the GraphQL servers**

When `email` is required:
![Screenshot from 2023-08-14 14-57-02](https://github.com/parameter1/company-update/assets/46794001/27297f97-1d79-4b36-96f5-f1a3f94d5f5e)
![Screenshot from 2023-08-14 14-57-22](https://github.com/parameter1/company-update/assets/46794001/0c2a69ec-1e3d-4f69-a5d3-1b875285914b)
![Screenshot from 2023-08-14 14-57-28](https://github.com/parameter1/company-update/assets/46794001/1a634845-5e8b-4429-856b-25af346404fc)
![Screenshot from 2023-08-14 14-58-00](https://github.com/parameter1/company-update/assets/46794001/d7e1313c-e792-4248-b930-fec5c3407a2b)

When no fields are required:
![Screenshot from 2023-08-14 15-02-19](https://github.com/parameter1/company-update/assets/46794001/826ca496-6a50-4d6b-9c8d-6855910451c3)

Presently only supports setting `email` to required but can be extended if we see a need for it "immediately" otherwise it should be a fairly modular thing to apply to other fields as need be.

2023-08-14 20:16 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Email Address Change for Client Portal](https://trello.com/c/5M6Qk7ct/388-email-address-change-for-client-portal)

2023-08-22 14:07 UTC, B77Mills requested changes

2023-08-22 14:07 UTC, B77Mills commented on services/app/app/controllers/portal/company.js
> +    console.log(requiredFields, requiredValuesSet);
@Shinsina  Remove me.

2023-08-22 14:07 UTC, B77Mills commented on services/app/app/controllers/portal/company.js
> +    const requiredValuesSet = requiredFields.map((fieldName) => this.get(`model.${fieldName}`)).filter((v) => v);
@Shinsina  I dont think we need the .filter part of this.

2023-08-22 15:15 UTC, solocommand commented on services/app/app/templates/components/company-card/contact.hbs
> +          change=(action onChange)
The input should also be `required` based on the `is-required` check.
```suggestion
          change=(action onChange)
          required=(is-required "email")
```

2023-08-22 17:56 UTC, B77Mills approved these changes

2023-08-22 17:58 UTC, merged