Removable leaders categories when configured
parameter1/company-update pull request #29
Opened 2023-10-31 19:43 UTC by Shinsina

Used https://github.com/parameter1/company-update/pull/24 as the primary reference point when enabling/configuring this functionality.

Showing updates being submitted:
![Screenshot from 2023-10-31 14-06-17](https://github.com/parameter1/company-update/assets/46794001/a25df518-b5b8-4440-ab17-bc4390d253cf)
![Screenshot from 2023-10-31 14-06-14](https://github.com/parameter1/company-update/assets/46794001/d33a5c7c-7ba0-41cc-9319-bc70d87e2612)
![Screenshot from 2023-10-31 14-06-20](https://github.com/parameter1/company-update/assets/46794001/b6cca806-786a-4f6e-9992-db13ecfb21b5)

Showing submitted additions actually updated:
![Screenshot from 2023-10-31 13-49-28](https://github.com/parameter1/company-update/assets/46794001/d410d423-8475-4606-9311-19a2c5885b68)

Showing removals being submitted:
![Screenshot from 2023-10-31 14-12-54](https://github.com/parameter1/company-update/assets/46794001/b754faf5-e3f5-4d4e-bfd1-03d5f429bf4d)

Show submitted removals actually updated:
![Screenshot from 2023-10-31 14-13-12](https://github.com/parameter1/company-update/assets/46794001/4a312535-796c-4256-9b28-c4d7a517c7e8)

2023-10-31 19:43 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Client Update Portal Leaders Question](https://trello.com/c/OWGOFW9a/386-client-update-portal-leaders-question)

2023-11-02 15:24 UTC, solocommand requested changes
Looks good. Only change would be to ensure that the user cannot de-select a leadership category if removal is not enabled via config.

2023-11-02 15:24 UTC, solocommand commented on services/app/app/controllers/portal/leadership.js
> +        selected.removeObject(id);
This should only happen if category removal is enabled -- the category shouldn't be removable in the UI if it's not going to be allowed in the submission.

2023-11-02 20:07 UTC, solocommand approved these changes

2023-11-06 16:24 UTC, merged