I18n Implementation on Company Update Form
parameter1/company-update pull request #3
Opened 2021-05-21 20:43 UTC by Shinsina

<img width="1920" alt="Screen Shot 2021-05-21 at 3 34 35 PM" src="https://user-images.githubusercontent.com/46794001/119196058-3b970a80-ba4b-11eb-969a-9eb90b9b6583.png">
<img width="1920" alt="Screen Shot 2021-05-21 at 3 38 18 PM" src="https://user-images.githubusercontent.com/46794001/119196065-3df96480-ba4b-11eb-8382-32ba2a5c3943.png">
<img width="1920" alt="Screen Shot 2021-05-21 at 3 38 15 PM" src="https://user-images.githubusercontent.com/46794001/119196067-3f2a9180-ba4b-11eb-9098-95be18e59410.png">
<img width="1920" alt="Screen Shot 2021-05-21 at 3 38 10 PM" src="https://user-images.githubusercontent.com/46794001/119196069-3fc32800-ba4b-11eb-8a52-f041448945e4.png">
<img width="1920" alt="Screen Shot 2021-05-21 at 3 36 15 PM" src="https://user-images.githubusercontent.com/46794001/119196071-3fc32800-ba4b-11eb-9017-9fba988d15d0.png">
<img width="1920" alt="Screen Shot 2021-05-21 at 3 35 17 PM" src="https://user-images.githubusercontent.com/46794001/119196072-405bbe80-ba4b-11eb-95a2-8c3260d87160.png">
<img width="1920" alt="Screen Shot 2021-05-21 at 3 35 12 PM" src="https://user-images.githubusercontent.com/46794001/119196075-405bbe80-ba4b-11eb-8fa5-0bfb1160417e.png">
<img width="1919" alt="Screen Shot 2021-05-21 at 3 34 57 PM" src="https://user-images.githubusercontent.com/46794001/119196076-40f45500-ba4b-11eb-885d-722a91c61601.png">
<img width="1920" alt="Screen Shot 2021-05-21 at 3 34 48 PM" src="https://user-images.githubusercontent.com/46794001/119196078-40f45500-ba4b-11eb-93e2-76c51ba74b38.png">

2021-05-21 20:43 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [How to solve for Mundo Leaders entries in Spanish and English](https://trello.com/c/oKzezqPm/50-how-to-solve-for-mundo-leaders-entries-in-spanish-and-english)

2021-05-24 13:22 UTC, Shinsina commented
This currently doesn't work on the review form YET, I need to update more graphql queries/fragments in order to resolve that.

2021-05-24 13:45 UTC, Shinsina commented
This should be all the forms updated correctly.

2021-05-24 14:51 UTC, solocommand requested changes
A few changes needed, notably using the ember-intl addon instead of a custom helper.

2021-05-24 14:51 UTC, solocommand commented on services/app/app/gql/queries/config.graphql
> +    lang
Call this `locale` please

2021-05-24 14:51 UTC, solocommand commented on docker-compose.yml
> +      APPLICATION_LANG_CHANGE: ${APPLICATION_LANG_CHANGE}
rename to `APP_LOCALE`

2021-05-24 14:51 UTC, solocommand commented on services/app/app/helpers/i18n.js
> +  console.log(lang)
Remove log

2021-05-24 14:51 UTC, solocommand commented on services/app/app/helpers/i18n.js
> +export function i18n ([lang, fieldLabelKey]) {
Don't pass in the language value, look it up from the configuration. This should use the [ember-intl](https://ember-intl.github.io/ember-intl/versions/master/docs/quickstart) package so we're not re-inventing everything here.

2021-05-24 14:51 UTC, solocommand commented on services/app/app/routes/application.js
> +    lang
Make these `locale` instead of `lang`.

2021-05-24 14:51 UTC, solocommand commented on services/app/app/templates/review/company.hbs
> +      lang=config.lang
None of this should be passed through anymore

2021-05-24 14:51 UTC, solocommand commented on services/graphql/src/env.js
> +  APPLICATION_LANG_CHANGE: str({ desc: 'If the language needs to be changed to something besides English', default: 'en' }),
```suggestion
  APP_LOCALE: str({ desc: 'The application locale', choices: ['en-us', 'es-mx'], default: 'en-us' }),
```

2021-05-24 17:56 UTC, Shinsina commented on services/graphql/src/env.js
> +  APPLICATION_LANG_CHANGE: str({ desc: 'If the language needs to be changed to something besides English', default: 'en' }),
<img width="1495" alt="Screen Shot 2021-05-24 at 12 51 13 PM" src="https://user-images.githubusercontent.com/46794001/119388037-65407380-bc8f-11eb-9463-6b281b8bb2d1.png">

2021-05-24 17:58 UTC, Shinsina commented
> A few changes needed, notably using the ember-intl addon instead of a custom helper.

<img width="1495" alt="Screen Shot 2021-05-24 at 12 51 13 PM" src="https://user-images.githubusercontent.com/46794001/119388294-b51f3a80-bc8f-11eb-9225-aa8d99fd8274.png">

2021-05-25 21:50 UTC, merged