Additional translations and fix to publish button.
parameter1/company-update pull request #4
Opened 2021-05-26 17:26 UTC by Shinsina

2021-05-26 17:29 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [How to solve for Mundo Leaders entries in Spanish and English](https://trello.com/c/oKzezqPm/50-how-to-solve-for-mundo-leaders-entries-in-spanish-and-english)

2021-05-26 17:39 UTC, brandonbk approved these changes

2021-05-27 19:05 UTC, solocommand requested changes

2021-05-27 19:05 UTC, solocommand commented on services/app/app/helpers/translations.js
> +    textLinkLabel: "Text link",
This should read `Link Text` not `Text link`. It is representative of the text value that should be included inside the A tag within the datacard -- "Cable and Hose Carrier Systems" in this example: 
![image](https://user-images.githubusercontent.com/1778222/119882384-fd3e9700-bef3-11eb-9f31-def982420755.png)

There should be a `Link URL` label to be added as well.

2021-05-27 19:05 UTC, solocommand commented on services/app/app/helpers/translations.js
> +    textLinkLabel: "Text link",
Keep quotes consistant -- use single quotes in this file.

2021-05-27 19:05 UTC, solocommand commented on services/app/app/helpers/translations.js
> +    promotionsP1Label: 'Review your companys product promotions',
This should be `your company's product`

2021-05-27 19:35 UTC, solocommand approved these changes

2021-05-27 19:35 UTC, merged